import React, { useEffect, useMemo, useState } from 'react';
import { BookOpen, CheckCircle, Eye, EyeOff, Headphones, PenTool, RefreshCw, Star } from 'lucide-react';

const PACKAGE_ID = '2026-09-20-k7m2p9x4q8';
const DATA_URL = `${import.meta.env.BASE_URL}homeworks/${PACKAGE_ID}/homework.json`;
const PROGRESS_KEY = `eugenia_homework_${PACKAGE_ID}_progress`;
const WRITING_KEY = `eugenia_homework_${PACKAGE_ID}_writing`;

function Questions({ questions, section, onComplete, label = 'Check answers' }) {
  const [answers, setAnswers] = useState({});
  const [checked, setChecked] = useState(false);
  const score = useMemo(() => questions.reduce((sum, question, index) => sum + (answers[index] === question.a ? 1 : 0), 0), [answers, questions]);
  const shuffled = useMemo(() => questions.map(question => ({ ...question, opt: [...question.opt].sort(() => Math.random() - 0.5) })), [questions]);
  return <div className="space-y-5">{shuffled.map((question, index) => {
    const selected = answers[index]; const correct = selected === question.a;
    return <article key={`${section}-${index}`} className="rounded-2xl border border-stone-200 dark:border-slate-700 bg-white dark:bg-slate-800 p-5">
      <p className="font-bold mb-4">{index + 1}. {question.q}</p>
      <div className="grid md:grid-cols-2 gap-3">{question.opt.map(option => <button key={option} onClick={() => setAnswers(current => ({ ...current, [index]: option }))} className={`p-3 rounded-xl border text-left ${selected === option ? 'border-blue-600 bg-blue-50 dark:bg-blue-950/40' : 'border-stone-200 dark:border-slate-600'}`}>{option}</button>)}</div>
      {checked && <p className={`mt-4 rounded-xl p-3 text-sm ${correct ? 'bg-emerald-50 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-200' : 'bg-rose-50 text-rose-800 dark:bg-rose-900/30 dark:text-rose-200'}`}>{correct ? 'Correct.' : <>Try again: <strong>{question.a}</strong></>}{question.why ? ` ${question.why}` : ''}</p>}
    </article>;
  })}<div className="flex flex-wrap gap-3 items-center pt-2"><button disabled={Object.keys(answers).length < questions.length} onClick={() => { setChecked(true); onComplete(section, score, questions.length); }} className="px-6 py-3 rounded-xl bg-slate-900 dark:bg-blue-600 text-white font-bold disabled:bg-stone-300">{label}</button>{checked && <><strong>Score: {score}/{questions.length}</strong><button onClick={() => { setAnswers({}); setChecked(false); }} className="px-5 py-3 rounded-xl border border-stone-300 dark:border-slate-600 font-bold"><RefreshCw className="inline w-4 h-4 mr-2"/>Retry</button></>}</div></div>;
}

export default function Homework20260920({ darkMode, toggleDarkMode, onOpenPrevious }) {
  const [data, setData] = useState(null); const [tab, setTab] = useState('notes'); const [error, setError] = useState(''); const [progress, setProgress] = useState({}); const [plays, setPlays] = useState(0); const [showScript, setShowScript] = useState(false); const [writing, setWriting] = useState('');
  useEffect(() => { fetch(DATA_URL).then(response => response.ok ? response.json() : Promise.reject(new Error(`Homework data returned ${response.status}`))).then(setData).catch(value => setError(value.message)); try { setProgress(JSON.parse(localStorage.getItem(PROGRESS_KEY) || '{}')); setWriting(localStorage.getItem(WRITING_KEY) || ''); } catch (_) {} }, []);
  const complete = (section, score, total) => { const next = { ...progress, [section]: { score, total } }; setProgress(next); try { localStorage.setItem(PROGRESS_KEY, JSON.stringify(next)); } catch (_) {} };
  const speak = () => { if ('speechSynthesis' in window && data) { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(data.listening.script); utterance.lang = 'en-GB'; utterance.rate = 0.88; window.speechSynthesis.speak(utterance); } setPlays(value => value + 1); };
  const tabs = [['notes', 'Review', BookOpen], ['grammar', 'Grammar', PenTool], ['vocabulary', 'Vocabulary', BookOpen], ['practice', 'Practice', PenTool], ['reading', 'Reading', BookOpen], ['listening', 'Listening', Headphones], ['writing', 'Writing', PenTool], ['quiz', 'Final Quiz', Star]];
  if (error) return <main className="p-10 text-rose-700">Could not load this homework: {error}</main>;
  if (!data) return <main className="min-h-screen grid place-items-center">Loading homework…</main>;
  const wordCount = writing.trim() ? writing.trim().split(/\s+/).length : 0;
  return <div className="min-h-screen bg-stone-50 dark:bg-slate-900 text-slate-800 dark:text-slate-100"><header className="sticky top-0 z-50 bg-white/90 dark:bg-slate-900/90 backdrop-blur border-b border-stone-200 dark:border-slate-800"><div className="max-w-6xl mx-auto px-4 py-3 flex flex-wrap items-center justify-between gap-3"><div><div className="font-extrabold">Eugenia's Homework Workspace</div><div className="text-xs text-stone-500 dark:text-slate-400">Homework 8 · {data.dateLabel}</div></div><div className="flex gap-2 items-center"><button className="px-4 py-2 rounded-xl bg-blue-600 text-white text-sm font-bold">Homework 8 · Latest</button><button onClick={onOpenPrevious} className="px-3 py-2 rounded-xl border border-stone-300 dark:border-slate-600 text-xs font-bold">Homework 7 · 9 Sep</button><button onClick={toggleDarkMode} aria-label="Toggle dark mode" className="p-2">{darkMode ? <Eye className="w-5 h-5"/> : <EyeOff className="w-5 h-5"/>}</button></div></div></header><main className="max-w-6xl mx-auto px-4 py-8 pb-20"><section className="rounded-3xl p-8 mb-8 bg-gradient-to-br from-blue-50 to-violet-50 dark:from-blue-950/40 dark:to-violet-950/30 border border-blue-100 dark:border-blue-900"><p className="text-xs font-black uppercase tracking-widest text-blue-700 dark:text-blue-300 mb-3">Lesson-based revision</p><h1 className="text-4xl font-extrabold font-serif mb-3">{data.title}</h1><p className="text-lg">{data.subtitle}</p></section><nav className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8 gap-2 mb-8 p-2 rounded-2xl bg-white dark:bg-slate-800 border border-stone-200 dark:border-slate-700">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`p-3 rounded-xl text-xs font-bold flex items-center justify-center gap-1 ${tab === id ? 'bg-slate-900 dark:bg-blue-600 text-white' : ''}`}><Icon className="w-4 h-4"/>{label}{progress[id] && <CheckCircle className="w-3 h-3 text-emerald-300"/>}</button>)}</nav>
  {tab === 'notes' && <section className="space-y-4">{data.lessonNotes.map((note, index) => <article key={note} className="rounded-2xl p-5 bg-white dark:bg-slate-800 border border-stone-200 dark:border-slate-700"><strong className="text-blue-600">{index + 1}. </strong>{note}</article>)}<button onClick={() => complete('notes', 1, 1)} className="px-6 py-3 rounded-xl bg-slate-900 dark:bg-blue-600 text-white font-bold">Mark review complete</button></section>}
  {tab === 'grammar' && <section className="space-y-5">{data.grammar.map(item => <article key={item.title} className="rounded-3xl p-6 bg-white dark:bg-slate-800 border border-stone-200 dark:border-slate-700"><h2 className="text-2xl font-extrabold font-serif mb-3">{item.title}</h2><p className="mb-4">{item.rule}</p><div className="grid md:grid-cols-3 gap-3">{item.examples.map(example => <p key={example} className="p-4 rounded-xl bg-blue-50 dark:bg-blue-900/20 font-semibold">{example}</p>)}</div></article>)}<button onClick={() => complete('grammar', 1, 1)} className="px-6 py-3 rounded-xl bg-slate-900 dark:bg-blue-600 text-white font-bold">Mark grammar complete</button></section>}
  {tab === 'vocabulary' && <section className="grid md:grid-cols-2 gap-4">{data.vocabulary.map(item => <article key={item.word} className="rounded-2xl p-5 bg-white dark:bg-slate-800 border border-stone-200 dark:border-slate-700"><h2 className="text-xl font-extrabold text-blue-700 dark:text-blue-300">{item.word}</h2><p className="mt-2">{item.meaning}</p><p className="mt-3 italic text-stone-600 dark:text-slate-300">{item.example}</p></article>)}<button onClick={() => complete('vocabulary', 1, 1)} className="md:col-span-2 justify-self-start px-6 py-3 rounded-xl bg-slate-900 dark:bg-blue-600 text-white font-bold">Mark vocabulary complete</button></section>}
  {tab === 'practice' && <Questions questions={data.practice} section="practice" onComplete={complete}/>}
  {tab === 'reading' && <section className="space-y-6"><article className="rounded-3xl p-7 bg-white dark:bg-slate-800 border border-stone-200 dark:border-slate-700"><p className="text-xs font-black uppercase text-blue-600">{data.reading.level} reading</p><h2 className="text-3xl font-extrabold font-serif my-4">{data.reading.title}</h2><p className="whitespace-pre-line leading-loose">{data.reading.text}</p></article><Questions questions={data.reading.questions} section="reading" onComplete={complete}/></section>}
  {tab === 'listening' && <section className="space-y-6"><article className="rounded-3xl p-7 bg-violet-50 dark:bg-violet-900/15 border border-violet-200 dark:border-violet-800"><h2 className="text-2xl font-extrabold font-serif mb-2">{data.listening.title}</h2><p>{data.listening.instructions}</p><div className="mt-5 flex gap-3"><button onClick={speak} className="px-5 py-3 rounded-xl bg-violet-600 text-white font-bold">Play audio</button><button disabled={plays < 2} onClick={() => setShowScript(value => !value)} className="px-5 py-3 rounded-xl border disabled:opacity-40">{showScript ? 'Hide' : 'Show'} transcript</button></div>{showScript && <p className="mt-5 whitespace-pre-line">{data.listening.script}</p>}</article><Questions questions={data.listening.questions} section="listening" onComplete={complete}/></section>}
  {tab === 'writing' && <section className="rounded-3xl p-7 bg-white dark:bg-slate-800 border border-stone-200 dark:border-slate-700"><h2 className="text-2xl font-extrabold font-serif mb-3">Writing for the next lesson</h2><p className="leading-relaxed">{data.writing.prompt}</p><textarea value={writing} onChange={event => setWriting(event.target.value)} rows={10} className="w-full mt-6 p-4 rounded-2xl border bg-stone-50 dark:bg-slate-900" placeholder="Write your paragraph here..."/><p className="mt-2 font-bold">{wordCount} words · target: 80–110</p><ul className="mt-5 grid sm:grid-cols-2 gap-2">{data.writing.checklist.map(item => <li key={item}>✓ {item}</li>)}</ul><button onClick={() => { try { localStorage.setItem(WRITING_KEY, writing); } catch (_) {} complete('writing', wordCount >= 80 && wordCount <= 110 ? 1 : 0, 1); }} className="mt-6 px-6 py-3 rounded-xl bg-slate-900 dark:bg-blue-600 text-white font-bold">Save writing</button></section>}
  {tab === 'quiz' && <section><article className="rounded-3xl p-6 mb-6 bg-amber-50 dark:bg-amber-900/15 border border-amber-200 dark:border-amber-800"><h2 className="text-2xl font-extrabold font-serif">Final formative quiz</h2><p>Aim for 16/20. This is practice, not a pass/fail test: use feedback and retry.</p></article><Questions questions={data.quiz} section="quiz" onComplete={complete} label="Submit quiz"/></section>}
  </main></div>;
}
